language: c

# Trusty Tahr release date: April 17, 2014
dist: trusty
sudo: required
#sudo: false
##group: beta

# Precise Pangolin release date: April 26, 2012
#dist: precise
#sudo: required

addons:
  apt:
    packages:
    - doxygen

os:
    - linux
    - osx

#osx_image:
#    - xcode7.3
#    #- xcode8

compiler:
    - clang
    - gcc

before_install:
    - build/travis/prebuild
#    - bash --version
#    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install freeglut; fi
#    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
#    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated bash || brew upgrade bash; fi
#    - bash --version

#install:

script:
    - build/travis/build

notifications:
    email:
        on_success: change
        on_failure: always

jobs:
  include:
    - stage: deploy
      if: branch = master
      script: ./build
      os: linux
      dist: xenial
      addons:
        apt:
          packages:
          - doxygen
      compiler: gcc
      deploy:
        provider: pages
        repo: mdadams/test-2-ghp
        target_branch: gh-pages
        local_dir: doc/html
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        on:
          branch: master
