os:
    - linux
    - osx

# Trusty Tahr release date: April 17, 2014
dist: trusty
sudo: required

language: c

compiler:
    - clang
    - gcc

addons:
  apt:
    packages:
    - doxygen
    - freeglut3-dev
    - freeglut3
    - libjpeg-turbo8
    - libjpeg-turbo8-dev

#before_install:
#    - build/travis/prebuild

#install:

script:
    - build/travis/build

notifications:
    email:
        on_success: change
        on_failure: always

jobs:
  include:
    - stage: deploy
      if: branch = master
      script:
        #- build/travis/prebuild
        - build/travis/build
      os: linux
      dist: xenial
      addons:
        apt:
          packages:
          - doxygen
          - freeglut3-dev
          - freeglut3
          - libjpeg-turbo8
          - libjpeg-turbo8-dev
      compiler: gcc
      deploy:
        provider: pages
        repo: mdadams/test-2-ghp
        target_branch: gh-pages
        local_dir: /tmp/jasper/static/install/share/doc/JasPer/html
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        on:
          branch: master
