dist: xenial
addons:
  apt:
    packages:
    - doxygen

language: c
compiler:
- clang
- gcc

script:
    - ./build

jobs:
  include:
    - stage: deploy
      branches:
        only:
          - experimental
      script: ./build
      os: xenial
      addons:
        apt:
          packages:
          - doxygen
      compiler: gcc
      deploy:
        provider: pages
        repo: mdadams/test-2-ghp
        target_branch: gh-pages
        local_dir: doc
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        on:
          branch: master
