#! /usr/bin/env bash

top_dir=$(pwd) || exit 1

#apt-get install doxygen || exit 1

(cd $top_dir/src && cmake -H. -Btmp_cmake) || exit 1
(cd $top_dir/src && cmake --build tmp_cmake) || exit 1

which doxygen

exit 0
